version: '3.4'

services:
  basketdb:
    container_name: basketdb
    restart: always
    ports: 
      - "6379:6379"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports: 
      - "5672:5672"
      - "15672:15672"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQUrl=rabbitmq
      - "ConnectionStrings:Redis=basketdb:6379"
    ports:
      - "5011:80"
    depends_on:
      - basketdb